# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-Override
version:      0.08
version_from: lib/Sub/Override.pm
installdirs:  site
requires:
    Sub::Uplevel:                  0
    Test::Exception:               0.21
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
