---
abstract: 'Perl extension for easily overriding subroutines'
author:
  - 'Curtis Poe <ovid@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Override
no_index:
  directory:
    - t
    - inc
requires:
  Test::Fatal: 0.010
  Test::More: 0.47
resources:
  repository: https://github.com/Ovid/sub-override
version: 0.09
